import type { Metadata } from "next";
import { Inter, Recursive } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "@/components/providers";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const recursive = Recursive({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(recursive.className, inter.className,)}
      >
        <Navbar/>
        <main
          className="flex grainy-light flex-col min-h-[calc(100vh-3.5rem-1px)]"
        >
          <div
            className="flex-1 flex flex-col h-full"
          >
            <Providers>
              {children}
            </Providers>
          </div>
          <Footer/>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
